#define IDD_MAIN                        101
#define IDD_HLP                         102
#define LANG_LIST                       1000
#define SUBFONT_LIST                    1001
#define REMOTE_LIST                     1002
#define RECEIVER_LIST                   1003
#define IDC_OK                          1010
#define IDC_HLP                         1011
#define IDC_STATIC                      1012
