#define IDD_MAIN                        101
#define IDD_HLP                         102
#define LANG_LIST                       1000
#define SUBFONT_LIST                    1001
#define REMOTE_LIST                     1002
#define RECEIVER_LIST                   1003
#define NVIDIA_LIST                     1004
#define AUDIO_LIST                      1005
#define TEMPOIMG                        1006
#define PHY_LIST                        1007
#define WIMO_LIST                       1008
#define WIFIWEP                         1009
#define WIFIESSID                       1010
#define IPGEEX                          1011
#define IPGAT                           1012
#define SMBUSER                         1013
#define SMBPWD                          1014
#define IDC_OK                          1020
#define IDC_HLP                         1021
#define IDC_STATIC                      1022
